version: '3.3'
services:
    run:
        ports:
            - '40000:80'
        container_name: Verifier
        environment:
            - SECRET=150712306138
            - ADMIN_PASSWORD=5566839853
            - DISCORD_GUILD=1138533378853961801
            - DISCORD_TOKEN=MTE0MzI4MzI0MDA5NDkyODk5Nw.GCwTgS.4yzjdIMLZE8cnkV-ID4qTw437AwtMmQzWecrwU
        restart: always
        image: run
